[package]
name = "Monie-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.5.0", features = ["full"] }
select = "0.5.0"
serde = { version = "1.0.125" }
serde_json = "1.0.64"
erased-serde = "0.3"
actix-web = "4.0.0-rc.3"
diesel = { version = "2.0.0", features = ["postgres", "r2d2", "uuid", "chrono"] }
diesel_migrations = "2.0.0"
actix-rt = "2.7.0"
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.15.0"
env_logger = "0.9.0"
lazy_static = "1.4"
listenfd = "1.0.0"
r2d2 = "0.8"
uuid = { version = "1.1.2", features = ["serde", "v4"] }