name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install protoc
        run: apt install -y protobuf-compiler
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag monie-release:$(date +%s)
